FROM quay.io/biocontainers/pyranges:0.0.120--pyh7cba7a3_0

# Update pip and install pysam package
RUN pip install pysam==0.22.1 pyBigWig==0.3.22

# Set the entry point to bash
ENTRYPOINT ["/bin/bash"]
