__default__:
  h_vmem: 4G
  tmem: 4G
  h_rt:  2:00:00
  submission_string: " "

peka:
  h_vmem: 22G
  tmem: 22G
  h_rt:  8:00:00
  submission_string: " "

cv_coverage_foreground:
  h_vmem: 12G
  tmem: 12G
  h_rt:  8:00:00
  submission_string: " "

cv_coverage_background:
  h_vmem: 12G
  tmem: 12G
  h_rt:  8:00:00
  submission_string: " "

per_motif_cv_coverage_foreground:
  h_vmem: 12G
  tmem: 12G
  h_rt:  8:00:00
  submission_string: " "

per_motif_cv_coverage_background:
  h_vmem: 12G
  tmem: 12G
  h_rt:  8:00:00
  submission_string: " "