library(tidyverse)

#' starting from bottom (i.e. the filename) of a UNIX-like filepath, return the directory name at a specified upstream 1-based level
getDirectoryAtLevel <- function(filepath, level) {
  # Split the filepath into components
  components <- rev(unlist(strsplit(dirname(filepath), "/")))
  
  # Check if the specified level is within the range of components
  if (level <= length(components) && level > 0) {
    # Extract the directory name at the specified level
    directory <- components[level]
    return(directory)
  } else {
    stop("Specified level is out of range.")
  }
}

#' Read in cv_coverage distribution tables for prespecified individual kmers from a directory generated by cv_coverage.smk
process_cv_cov_kmer <- function(base_dir, kmers, return_paths = FALSE) {
  
  # step 1 - define regex for kmer coverage file
  # file ends in <kmer>.tsv
  # ends in one of the kmers.tsv
  kmer_regex <- paste("(", paste(kmers, collapse = "|"),")","\\.tsv$",sep = "")
  
  # CGUGUG/cv_coverage_foreground/results/d3utr_pas_proximal.foreground_genome_20_CGUGUG.tsv
  # don't want to assume name of foreground/background or the bas
  dbrn_paths <- list.files(path = base_dir,
                           pattern = kmer_regex,
                           recursive = T,
                           full.names = T)  
  
  # return(dbrn_paths)
  
  # now need to check that file name only contains a single kmer
  # this prevents pulling out paths with combos of multiple kmers
  dbrn_paths <- dbrn_paths[str_count(basename(dbrn_paths), paste(kmers, collapse = "|")) == 1]
  
  # now construct 'kmer_comparison_ids'
  # combo of genomic region (bleedthrough, distal_apa etc.), kmer & region type (foreground/background)
  # e.g.
  # data/peka_papa/2023-11-16_papa_cryptics_kmer6_window_250_distal_window_500_relpos_0/cv_coverage/spliced_exonstart/UGUGCG/cv_coverage_foreground/results/spliced_exonstart.foreground_genome_20_UGUGCG.tsv"
  # region_type = 4 dirs back in path
  # kmer = 3 dirs back in path
  # group = 2 dirs back in path, remove cv_coverage
  region_type <- sapply(dbrn_paths, function(p) getDirectoryAtLevel(p, 4))
  kmer <- sapply(dbrn_paths, function(p) getDirectoryAtLevel(p, 3))
  group <- str_remove(sapply(dbrn_paths, function(p) getDirectoryAtLevel(p, 2)), "^cv_coverage_")
  
  kmer_comparison_ids <- paste(region_type, kmer, group, sep = ";")
  
  # set names to constructed IDs
  dbrn_paths <- dbrn_paths %>%
    set_names(kmer_comparison_ids) 
  
  if (return_paths) {
    return(dbrn_paths)
  }
  
  # now read in dfs & combine into one
  dbrn_tbl <- map(dbrn_paths, 
                  ~ read_tsv(.x,
                             col_names = c("rel_posn", "rel_occur"),
                             skip = 1, # skip defined header
                             show_col_types = F
                  )
  ) %>%
    bind_rows(.id = "comparison_id")  
  
  # extract out region_type, kmer & group from comparison_id
  separate(dbrn_tbl, comparison_id, into = c("region_type", "kmer", "group"), sep = ";")
  
}

#####

### Process individual CV coverage outputs for TDP-43  enriched kmers taken from Halleger et al. 2021
yg_6mers <- c("UGUGUG", "GUGUGU","UGUGCG", "UGCGUG","CGUGUG","GUGUGC")
ya_6mers <- c("AUGUGU", "GUAUGU", "GUGUAU", "UGUGUA", "UGUAUG", "UGCAUG")
aa_6mers <- c("GUGUGA", "AAUGAA", "GAAUGA", "UGAAUG", "AUGAAU", "GUGAAU", "GAAUGU", "UUGAAU")

yg_6mer_dbrn_tbl <- process_cv_cov_kmer("data/peka_papa/2023-11-27_papa_cryptics_fixed_kmer6_window_250_distal_window_500_relpos_0/cv_coverage", yg_6mers) %>%
  mutate(kmer_group = "yg_6mer")
ya_6mer_dbrn_tbl <- process_cv_cov_kmer("data/peka_papa/2023-11-27_papa_cryptics_fixed_kmer6_window_250_distal_window_500_relpos_0/cv_coverage", ya_6mers) %>%
  mutate(kmer_group = "ya_6mer")
aa_6mer_dbrn_tbl <- process_cv_cov_kmer("data/peka_papa/2023-11-27_papa_cryptics_fixed_kmer6_window_250_distal_window_500_relpos_0/cv_coverage", aa_6mers) %>%
  mutate(kmer_group = "aa_6mer")

# remove any previous background types
yg_6mer_dbrn_tbl <- filter(yg_6mer_dbrn_tbl, str_ends(region_type, "background_shsy5y"))
ya_6mer_dbrn_tbl <- filter(ya_6mer_dbrn_tbl, str_ends(region_type, "background_shsy5y"))
aa_6mer_dbrn_tbl <- filter(aa_6mer_dbrn_tbl, str_ends(region_type, "background_shsy5y"))


unique(yg_6mer_dbrn_tbl$region_type)
unique(ya_6mer_dbrn_tbl$region_type)
unique(aa_6mer_dbrn_tbl$region_type)

setdiff(yg_6mers, unique(yg_6mer_dbrn_tbl$kmer))
setdiff(ya_6mers, unique(ya_6mer_dbrn_tbl$kmer))
setdiff(aa_6mers, unique(aa_6mer_dbrn_tbl$kmer))


if (!dir.exists("processed/peka/papa")) {dir.create("processed/peka/papa", recursive = T)}

write_tsv(yg_6mer_dbrn_tbl,
         "processed/peka/papa/2023-11-27_papa_cryptics_cvcoverage_window_500.yg_6mers.per_kmer_distribution_genome.tsv",
         col_names = T)

write_tsv(ya_6mer_dbrn_tbl,
         "processed/peka/papa/2023-11-27_papa_cryptics_cvcoverage_window_500.ya_6mers.per_kmer_distribution_genome.tsv",
         col_names = T)

write_tsv(aa_6mer_dbrn_tbl,
          "processed/peka/papa/2023-11-27_papa_cryptics_cvcoverage_window_500.aa_6mers.per_kmer_distribution_genome.tsv",
          col_names = T)