library(tidyverse)

#' starting from bottom (i.e. the filename) of a UNIX-like filepath, return the directory name at a specified upstream 1-based level
getDirectoryAtLevel <- function(filepath, level) {
  # Split the filepath into components
  components <- rev(unlist(strsplit(dirname(filepath), "/")))
  
  # Check if the specified level is within the range of components
  if (level <= length(components) && level > 0) {
    # Extract the directory name at the specified level
    directory <- components[level]
    return(directory)
  } else {
    stop("Specified level is out of range.")
  }
}

#' Read in cv_coverage distribution tables for prespecified individual kmers from a directory generated by cv_coverage.smk
process_cv_cov_kmer <- function(base_dir, kmers, return_paths = FALSE) {
  
  # step 1 - define regex for kmer coverage file
  # file ends in <kmer>.tsv
  # ends in one of the kmers.tsv
  kmer_regex <- paste("(", paste(kmers, collapse = "|"),")","\\.tsv$",sep = "")
  
  # CGUGUG/cv_coverage_foreground/results/d3utr_pas_proximal.foreground_genome_20_CGUGUG.tsv
  # don't want to assume name of foreground/background or the bas
  dbrn_paths <- list.files(path = base_dir,
                           pattern = kmer_regex,
                           recursive = T,
                           full.names = T)  
  
  # return(dbrn_paths)
  
  # now need to check that file name only contains a single kmer
  # this prevents pulling out paths with combos of multiple kmers
  dbrn_paths <- dbrn_paths[str_count(basename(dbrn_paths), paste(kmers, collapse = "|")) == 1]
  
  # now construct 'kmer_comparison_ids'
  # combo of genomic region (bleedthrough, distal_apa etc.), kmer & region type (foreground/background)
  # e.g.
  # data/peka_papa/2023-11-16_papa_cryptics_kmer6_window_250_distal_window_500_relpos_0/cv_coverage/spliced_exonstart/UGUGCG/cv_coverage_foreground/results/spliced_exonstart.foreground_genome_20_UGUGCG.tsv"
  # region_type = 4 dirs back in path
  # kmer = 3 dirs back in path
  # group = 2 dirs back in path, remove cv_coverage
  region_type <- sapply(dbrn_paths, function(p) getDirectoryAtLevel(p, 4))
  kmer <- sapply(dbrn_paths, function(p) getDirectoryAtLevel(p, 3))
  group <- str_remove(sapply(dbrn_paths, function(p) getDirectoryAtLevel(p, 2)), "^cv_coverage_")
  
  kmer_comparison_ids <- paste(region_type, kmer, group, sep = ";")
  
  # set names to constructed IDs
  dbrn_paths <- dbrn_paths %>%
    set_names(kmer_comparison_ids) 
  
  if (return_paths) {
    return(dbrn_paths)
  }
  
  # now read in dfs & combine into one
  dbrn_tbl <- map(dbrn_paths, 
                  ~ read_tsv(.x,
                             col_names = c("rel_posn", "rel_occur"),
                             skip = 1, # skip defined header
                             show_col_types = F
                  )
  ) %>%
    bind_rows(.id = "comparison_id")  
  
  # extract out region_type, kmer & group from comparison_id
  separate(dbrn_tbl, comparison_id, into = c("region_type", "kmer", "group"), sep = ";")
  
}

#####


# find paths to all kmer distrivution tables for different comparisons
# commenting out as may be influence by new set up with cv_coverage.smk
# to be safe, should generate paths for each comparison name found under the given base directory
# dbrn_paths <- list.files(path = "data/peka_papa/2023-11-16_papa_cryptics_kmer6_window_250_distal_window_500_relpos_0",
#                          pattern = "_UGUGUG_GUGUGU.tsv$",
#                          recursive = T,
#                          full.names = T)
# dbrn_paths
# 
# # get the 'comparison name' from the name of bed file
# comparison_names <- str_remove(basename(dbrn_paths), "\\.(foreground|background)_genome_20_UGUGUG_GUGUGU.tsv$")
# # want to go two folders back to whether foreground or background seqs (cv_coverage_<foreground/background>)
# # then extract whether foreground/background (final field after split by _)
# region_names <- str_split_i(basename(dirname(dirname(dbrn_paths))), "_", 3)
# # combine to construct final ID
# comparison_ids <- paste(comparison_names, region_names, sep = ";")
# 
# # read in tables, combine into single df
# dbrn_tbl <- dbrn_paths %>%
#   set_names(comparison_ids) %>%
#   map(~ read_tsv(.x,
#                  col_names = c("rel_posn", "rel_occur"),
#                  skip = 1, # skip defined header
#                  show_col_types = F
#                  )
#       ) %>%
#   bind_rows(.id = "comparison_id")
# 
# 
# 
# 
# 
# # construct comparison name - first element before ;
# # region type - exonstart / pas / pas_proximal / pas_distal
# # group = foreground/background
# dbrn_tbl <- dbrn_tbl %>%
#   separate(comparison_id, into = c("comparison_name", "group"), sep = ";", remove = F) %>%
#   mutate(region_type = str_extract(comparison_name,  paste(c("pas$","exonstart", "pas_proximal", "pas_distal"), collapse = "|")),
#          .after = comparison_name)
# 
# if (!dir.exists("processed/peka/papa")) {dir.create("processed/peka/papa", recursive = T)}
# 
# write_tsv(dbrn_tbl,
#           "processed/peka/papa/2023-11-16_papa_cryptics_cvcoverage_window_500.gugugu_ugugug.distribution_genome.tsv",
#           col_names = T)


### Alternative - process groups of motifs

# taken from Halleger et al. 2021
yg_6mers <- c("UGUGUG", "GUGUGU","UGUGCG", "UGCGUG","CGUGUG","GUGUGC")
ya_6mers <- c("AUGUGU", "GUAUGU", "GUGUAU", "UGUGUA", "UGUAUG", "UGCAUG")

yg_6mer_dbrn_tbl <- process_cv_cov_kmer("data/peka_papa/2023-11-16_papa_cryptics_kmer6_window_250_distal_window_500_relpos_0/cv_coverage", yg_6mers) %>%
  mutate(kmer_group = "yg_6mer")
ya_6mer_dbrn_tbl <- process_cv_cov_kmer("data/peka_papa/2023-11-16_papa_cryptics_kmer6_window_250_distal_window_500_relpos_0/cv_coverage", ya_6mers) %>%
  mutate(kmer_group = "ya_6mer")

unique(yg_6mer_dbrn_tbl$region_type)
unique(yg_6mer_dbrn_tbl$kmer)
unique(yg_6mer_dbrn_tbl$group)

unique(ya_6mer_dbrn_tbl$region_type)
unique(ya_6mer_dbrn_tbl$kmer)
unique(ya_6mer_dbrn_tbl$group)

if (!dir.exists("processed/peka/papa")) {dir.create("processed/peka/papa", recursive = T)}

write_tsv(yg_6mer_dbrn_tbl,
         "processed/peka/papa/2023-11-19_papa_cryptics_cvcoverage_window_500.yg_6mers.per_kmer_distribution_genome.tsv",
         col_names = T)

write_tsv(ya_6mer_dbrn_tbl,
         "processed/peka/papa/2023-11-19_papa_cryptics_cvcoverage_window_500.ya_6mers.per_kmer_distribution_genome.tsv",
         col_names = T)