library(tidyverse)

#' Prepare Heatmap Dataframe
#'
#' Prepare a dataframe containing sample-wise PAS usage differences for plotting as a heatmap of samples (x) * events (y)
#'
#' @param df A dataframe containing sample-wise differences in PAS usage, (e.g. `ppau_delta_paired_cryp`).
#' @param le_id_order A vector specifying the plotting order (factor levels) of `plot_le_id` column (e.g `ppau_order_cryp_median_gn_5`).
#'
#' @return A dataframe ready for generating a heatmap
prep_heatmap_df <- function(df, le_id_order) {
  # Define the required columns
  required_columns <- c("plot_le_id", "paired_delta_ppau_neg_pos", 
                        "simple_event_type", "patient_id")
  
  # Check if all required columns are present
  missing_columns <- setdiff(required_columns, colnames(df))
  if (length(missing_columns) > 0) {
    stop("The following required columns are missing: ", paste(missing_columns, collapse = ", "))
  }
  
  df %>%
    mutate(
      paired_delta_ppau_neg_pos = paired_delta_ppau_neg_pos * 100,
      plot_le_id = factor(plot_le_id, levels = le_id_order),
      plot_event_type = case_when(
        simple_event_type == "spliced" ~ "ALE",
        simple_event_type == "bleedthrough" ~ "IPA",
        simple_event_type == "distal_3utr_extension" ~ "3'Ext",
        str_detect(simple_event_type, ",") ~ "Complex",
        TRUE ~ "3'Shortening"
      ),
      plot_event_type = factor(plot_event_type, levels = c("ALE", "IPA", "3'Ext", "Complex", "3'Shortening")),
      plot_patient_id = str_extract(patient_id, "\\d$"),
      plot_patient_id = factor(plot_patient_id, levels = c("2", "6", "7", "1", "3", "4", "5"))
    )
}


#' Plot Heatmap of sample-wise differences in PAS usage between nuclei populations
#'
#' This function creates a heatmap visualization using the processed dataframe from `prep_heatmap_df`. 
#' 
#'
#' @param df A dataframe, the output of `prep_heatmap_df`, containing the processed data for plotting.
#' @param plot_theme A ggplot2 theme, defaulting to `theme_bw(base_size = 20)`.
#' @param plot_labs A ggplot2 labs call to name axes, defaulting to `labs(x = "", y = "")`.
#' @param theme_args A list of theme arguments for fine-tuning the appearance. Defaults are set within the function.
#'
#' @return A ggplot object object (generated by geom_tile())
#'
plot_heatmap <- function(df,
                         plot_labs = labs(x = "", y = ""),
                         fill_name = "Delta polyA usage % (TDPnegative - TDPpositive)",
                         plot_theme = theme_bw(base_size = 20), 
                         theme_args = list(
                           legend.position = "top",
                           legend.key.size = unit(20, "mm"),
                           legend.key.width = unit(25, "mm"),
                           legend.key.height = unit(10, "mm")
                         )) {
  # Define the required columns
  required_columns <- c("plot_event_type", "plot_patient_id", 
                        "plot_le_id", "paired_delta_ppau_neg_pos")
  
  # Check if all required columns are present
  missing_columns <- setdiff(required_columns, colnames(df))
  if (length(missing_columns) > 0) {
    stop("The following required columns are missing: ", paste(missing_columns, collapse = ", "))
  }
  
  # Create the heatmap
  heatmap_plot <- ggplot(df, aes(x = plot_patient_id,
                                          y = plot_le_id,
                                          fill = paired_delta_ppau_neg_pos)) +
    facet_wrap("~ plot_event_type", scales = "free_y") +
    geom_tile() +
    scale_fill_gradientn(name = fill_name,
                         colours = c("#998ec3", "#f7f7f7", "#f1a340"),
                         limits = c(-100, 100),
                         breaks = seq(-100, 100, 20)) +
    plot_theme +
    plot_labs +
    do.call(theme, theme_args)
  
  return(heatmap_plot)
}



ppau_delta_paired_median_all <- read_tsv("processed/liu_facs/2024-11-20_liu_facs_decoys_delta_ppau.all_samples.all_ales.tsv.gz")
ppau_delta_paired_median_disease <- read_tsv("processed/liu_facs/2024-11-20_liu_facs_decoys_delta_ppau.subtype_split.all_ales.tsv.gz")
ppau_delta_paired <- read_tsv("processed/liu_facs/2024-11-20_liu_facs_decoys_per_sample_delta_ppau.all_ales.tsv.gz")
ppau_delta_mean_cryp <- read_tsv("processed/liu_facs/2024-11-20_liu_facs_decoys_popn_delta_ppau.cryptics.tsv")


# get an order of le_ids according to ranks of median delta between negative and positive
# (this puts events with most consistent enrichment at the top of the heatmap)
ppau_order_cryp <- ppau_delta_paired_median_all %>%
  filter(cryptic_status) %>%
  # rank deltas from largest to smallest, giving same rank if identical delta
  mutate(rank_mean_up = min_rank(desc(mean_paired_delta_ppau)),
         rank_median_up = min_rank(desc(median_paired_delta_ppau))) %>%
  arrange(rank_median_up, rank_mean_up)

# get ranked order of IDs from most enriched to least enriched 
ppau_order_cryp_median_gn <- ppau_order_cryp %>%
  arrange(rank_median_up) %>%
  pull(plot_le_id)

# get a df of events passing the median threshold
ppau_order_cryp_min5 <- ppau_order_cryp %>%
  filter(median_paired_delta_ppau > 0.05)

# 
delta_paired_summary <- ppau_delta_paired_median_all %>%
  filter(cryptic_status) %>%
  summary(paired_delta_ppau_neg_pos)

# List of IDs with at least 5 % median delta
ppau_order_cryp_median_gn_5 <- ppau_order_cryp %>%
  filter(median_paired_delta_ppau > 0.05) %>%
  pull(plot_le_id)

# Decay of number of enriched events as increase the delta cut-off
cryp_median_min_delta_n <- seq(0,0.25,0.05) %>%
  set_names() %>%
  map(~ ppau_order_cryp %>%
        filter(median_paired_delta_ppau > .x) %>%
        summarise(n_events = n_distinct(plot_le_id))
  ) %>%
  bind_rows(.id = "min_median_delta_pau")

# Decay of number of enriched events as increase the delta cut-off with counts split by event type
cryp_median_min_delta_nevent_by_type <- seq(0,0.25,0.05) %>%
  set_names() %>%
  map(~ ppau_order_cryp %>%
        mutate(enriched = median_paired_delta_ppau > .x) %>%
        group_by(simple_event_type) %>%
        summarise(n_enriched = sum(enriched),
                  n = n_distinct(plot_le_id),
        )
  ) %>%
  bind_rows(.id = "median_delta_cutoff")

# Generate plot-ready df - all events with at least +5 % delta median paired PPAU
# Order IDs in descending order of enrichment in each category
ppau_delta_paired_cryp <- ppau_delta_paired %>%
  filter(cryptic_status)

plot_df_median_5_delta <- ppau_delta_paired_cryp %>%
  filter(plot_le_id %in% ppau_order_cryp_median_gn_5) %>%
  prep_heatmap_df(le_id_order = rev(ppau_order_cryp_median_gn_5))

median5_std_events_heatmap <- plot_df_median_5_delta %>%
  filter(plot_event_type %in% c("ALE", "IPA", "3'Ext")) %>%
  plot_heatmap(fill_name ="Delta PAS usage %\n(TDPnegative - TDPpositive)",
               plot_labs = labs(x = "",
                                y = "",
                                ),
               plot_theme = theme_bw(base_size = 14),
               theme_args = list(
                 legend.position = "top",
                 legend.key.size = unit(20*0.75, "mm"),
                 legend.key.width = unit(25*0.75, "mm"),
                 legend.key.height = unit(10*0.75, "mm")
               ))

median5_std_events_heatmap

# heatmaps for other categories passing enrichment criteria
median5_other_events_heatmap <- plot_df_median_5_delta %>%
  filter(!plot_event_type %in% c("ALE", "IPA", "3'Ext")) %>%
  plot_heatmap()

median5_other_events_heatmap


# # Heatmap for NYGC selective events that aren't found in FACS-seq (manually curated)
# nygc_sel_only <- c("SYNJ2", "PHF2", "SERGEF", "PATJ", "DLGAP1") %>%
#   fct_inorder()
# 
# plot_df_nygc_sel_only <- ppau_delta_paired_cryp %>%
#   filter(gene_name %in% nygc_sel_only) %>%
#   prep_heatmap_df(le_id_order = rev(levels(nygc_sel_only)))
# 
# nygc_sel_only_heatmap <- plot_heatmap(plot_df_nygc_sel_only) +
#   geom_text(aes(label = round(paired_delta_ppau_neg_pos, 2))) +
#   scale_fill_gradient2(name = "Delta polyA usage % (TDPnegative - TDPpositive)",
#                        low = "#998ec3",
#                        mid = "#f7f7f7",
#                        high = "#f1a340",
#                        midpoint = 0,
#                        # limits = c(-1, 1),
#                        breaks = seq(-20, 20, 5)
#   )


if (!dir.exists("processed/liu_facs")) {dir.create("processed/liu_facs", recursive = T)}

# standard heatmaps
ggsave("2024-11-26_liu_facs_cryptic_median_delta_05_facet.std_event_types.png",
       plot = median5_std_events_heatmap,
       path = "processed/liu_facs",
       height = 150,
       width = 200,
       units = "mm",
       dpi = "retina")
ggsave("2024-11-26_liu_facs_cryptic_median_delta_05_facet.std_event_types.pdf",
       plot = median5_std_events_heatmap,
        path = "processed/liu_facs",
        height = 150,
        width = 200,
        units = "mm",
        dpi = "retina")

# other event types
ggsave("2024-11-21_liu_facs_cryptic_median_delta_05_facet.other_event_types.png",
       plot = median5_other_events_heatmap,
       path = "processed/liu_facs",
       height = 8,
       width = 12,
       units = "in",
       dpi = "retina")

ggsave("2024-11-21_liu_facs_cryptic_median_delta_05_facet.other_event_types.svg",
       plot = median5_other_events_heatmap,
       path = "processed/liu_facs",
       height = 10,
       width = 15,
       device = svg,
       units = "in",
       dpi = "retina")

ggsave("2024-11-21_liu_facs_cryptic_median_delta_05_facet.other_event_types.pdf",
       plot = median5_other_events_heatmap,
       path = "processed/liu_facs",
       height = 10,
       width = 15,
       units = "in",
       dpi = "retina")

# NYGC selective only
# ggsave("2024-11-21_liu_facs_nygc_selective_only.ales.png",
#        plot = nygc_sel_only_heatmap,
#        path = "processed/liu_facs",
#        height = 8,
#        width = 12,
#        units = "in",
#        dpi = "retina")
# 
# ggsave("2024-11-21_liu_facs_nygc_selective_only.ales.pdf",
#        plot = nygc_sel_only_heatmap,
#        path = "processed/liu_facs",
#        height = 8,
#        width = 12,
#        units = "in",
#        dpi = "retina")

# enriched count tables
write_tsv(cryp_median_min_delta_nevent_by_type, "processed/liu_facs/2024-11-21_liu_facs_min_delta_range_numevents_eventtype.tsv", col_names = T)
write_tsv(cryp_median_min_delta_n, "processed/liu_facs/2024-11-21_liu_facs_min_delta_cutoffs_numevents_all.tsv", col_names = T)
# enriched table (with ranks and summarised ppau)
write_tsv(ppau_order_cryp_min5, "processed/liu_facs/2024-11-22_liu_facs_median_delta_5.delta_ppau.all_samples.cryptics.tsv", col_names = T)
          