library(tidyverse)

#' Prepare Heatmap Dataframe
#'
#' Prepare a dataframe containing sample-wise PAS usage differences for plotting as a heatmap of samples (x) * events (y)
#'
#' @param df A dataframe containing sample-wise differences in PAS usage, (e.g. `ppau_delta_paired_cryp`).
#' @param le_id_order A vector specifying the plotting order (factor levels) of `plot_le_id` column (e.g `ppau_order_cryp_median_gn_5`).
#'
#' @return A dataframe ready for generating a heatmap
prep_heatmap_df <- function(df, le_id_order) {
  # Define the required columns
  required_columns <- c("plot_le_id", "paired_delta_ppau_neg_pos", 
                        "simple_event_type", "patient_id")
  
  # Check if all required columns are present
  missing_columns <- setdiff(required_columns, colnames(df))
  if (length(missing_columns) > 0) {
    stop("The following required columns are missing: ", paste(missing_columns, collapse = ", "))
  }
  
  df %>%
    mutate(
      paired_delta_ppau_neg_pos = paired_delta_ppau_neg_pos * 100,
      plot_le_id = factor(plot_le_id, levels = le_id_order),
      plot_event_type = case_when(
        simple_event_type == "spliced" ~ "ALE",
        simple_event_type == "bleedthrough" ~ "IPA",
        simple_event_type == "distal_3utr_extension" ~ "3'Ext",
        str_detect(simple_event_type, ",") ~ "Complex",
        TRUE ~ "3'Shortening"
      ),
      plot_event_type = factor(plot_event_type, levels = c("ALE", "IPA", "3'Ext", "Complex", "3'Shortening")),
      plot_patient_id = str_extract(patient_id, "\\d$"),
      plot_patient_id = factor(plot_patient_id, levels = c("2", "6", "7", "1", "3", "4", "5"))
    )
}


#' Plot Heatmap of sample-wise differences in PAS usage between nuclei populations
#'
#' This function creates a heatmap visualization using the processed dataframe from `prep_heatmap_df`. 
#' 
#'
#' @param df A dataframe, the output of `prep_heatmap_df`, containing the processed data for plotting.
#' @param plot_theme A ggplot2 theme, defaulting to `theme_bw(base_size = 20)`.
#' @param plot_labs A ggplot2 labs call to name axes, defaulting to `labs(x = "", y = "")`.
#' @param theme_args A list of theme arguments for fine-tuning the appearance. Defaults are set within the function.
#'
#' @return A ggplot object object (generated by geom_tile())
#'
plot_heatmap <- function(df,
                         plot_labs = labs(x = "", y = ""), 
                         plot_theme = theme_bw(base_size = 20), 
                         theme_args = list(
                           legend.position = "top",
                           legend.key.size = unit(20, "mm"),
                           legend.key.width = unit(25, "mm"),
                           legend.key.height = unit(10, "mm")
                         )) {
  # Define the required columns
  required_columns <- c("plot_event_type", "plot_patient_id", 
                        "plot_le_id", "paired_delta_ppau_neg_pos")
  
  # Check if all required columns are present
  missing_columns <- setdiff(required_columns, colnames(df))
  if (length(missing_columns) > 0) {
    stop("The following required columns are missing: ", paste(missing_columns, collapse = ", "))
  }
  
  # Create the heatmap
  heatmap_plot <- ggplot(df, aes(x = plot_patient_id,
                                 y = plot_le_id,
                                 fill = paired_delta_ppau_neg_pos)) +
    facet_wrap("~ plot_event_type", scales = "free_y") +
    geom_tile() +
    scale_fill_gradientn(name = "Delta polyA usage % (TDPnegative - TDPpositive)",
                         colours = c("#998ec3", "#f7f7f7", "#f1a340"),
                         limits = c(-100, 100),
                         breaks = seq(-100, 100, 20)) +
    plot_theme +
    plot_labs +
    do.call(theme, theme_args)
  
  return(heatmap_plot)
}

